# Product Lines Reference Data
# Schema Version: 1.0
# Description: 产品线 reference data for annuity performance domain

schema_version: "1.0"
description: "产品线 reference data for annuity performance domain"

data:
  - 产品线代码: "PL001"
    产品线名称: "企业年金"
  - 产品线代码: "PL002"
    产品线名称: "职业年金"
  - 产品线代码: "PL003"
    产品线名称: "养老保障"
  - 产品线代码: "PL004"
    产品线名称: "个人养老金"
