# Company ID Overrides - Plan Code Mappings (Priority 1)
# Story 6.x: Internal Mapping Tables and Database Schema
#
# Format: plan_code: company_id
# Example:
#   "FP0001": "614810477"
#
# This file maps plan codes to company IDs.
# P1-P4 data will be migrated from Layer 2 (Database Cache) in future.
#
# New Pipeline Priority Order:
#   P1: plan (本文件 - 计划代码)
#   P2: account_name (年金账户名)
#   P3: account (年金账户号)
#   P4: name (客户名称)
#   P5: hardcode (组合映射特殊情况)

# 国寿集合计划系列-中国人寿养老保险股份有限公司
FP0001: "614810477"
FP0002: "614810477"

# 建信养老集合计划-建信养老金管理有限责任公司
FP0003: "610081428"

# 长江金色晚晴-长江养老保险股份有限公司
XNP596: "601038164"

# 人民养老合计划-中国人民养老保险有限责任公司
XNP717: "616273364"

# 农银金穗养老壹号企业年金集合计划-农银国际（中国）投资有限公司
XNP706: "600027278"

# 工银集合计划系列-中国工商银行股份有限公司
XNP466: "603968573"
XNP467: "603968573"

# 大连社保转制计划-平安养老保险股份有限公司大连分公司
SC002: "604809109"

# 云南省过渡计划-平安养老保险股份有限公司云南分公司
SC007: "602790403"
